#!/usr/bin/env bash

set -euo pipefail

Help() {
        echo contribufind help
        echo opts:
        echo -l: specify labels to filter issues for
        echo -h: this manual    
}

search_by_label() {
	local labels="$1"
	local gh_args=()
	
	IFS=',' read -ra label_array <<< "$labels"

	for label in "${label_array[@]}"; do 
		gh_args+=(--label "$label")
	done
	
	gh search issues "${gh_args[@]}"
}

search_by_language() {
	local languages="$1"
	local gh_args=()
	
	IFS=',' read -ra language_array <<< "$languages"

	for language in "${language_array[@]}"; do 
		gh_args+=(--language "$language")
	done
	
	gh search issues "${gh_args[@]}"
}
