#!/usr/bin/env bash

set -euo pipefail

Help() {
        echo contribufind help
        echo opts:
        echo -l: specify a label to search issues for
        echo -L: specify an array of labels to search issues for
        echo -h: this manual    
}

search_by_label() {
	local label="$1"
        gh search issues -- "label:$label"
}


