#!/usr/bin/env bash

set -euo pipefail

Help() {
        echo contribufind help
        echo opts:
        echo -l: specify a label to search issues for
        echo -L: specify an array of labels to search issues for
        echo -h: this manual    
}

search_by_label() {
	local labels="$1"
	local gh_args=()
	
	IFS=',' read -ra label_array <<< "$labels"

	for label in "${label_array[@]}"; do 
		gh_args+=(--label "$label")
	done
	
	gh search issues "${gh_args[@]}"
}
