#!/usr/bin/env bash

set -euo pipefail

. ./api


# only looks for issues rn
while getopts ":hl:" opt; do
	case $opt in
		:)
			Help;;	
		h)
			Help;;
		l)
			search_by_label "$OPTARG";;
		*)
			echo "error parsing positional args" >&2
			exit 1
			;;
	esac	
done
