#!/usr/bin/env bash

Help() {
	echo contribufind help
	echo opts:
	echo -l: specify a label to search issues for
	echo -L: specify an array of labels to search issues for
	echo -h: this manual	
}


# only looks for issues rn
while getopts ":hlL" opt; do
	case $opt in
		h)
			Help
			;;
		l)
			gh search issues -- "label:$OPTARG"
			;;
		L)
			label_str=''
			for label in $OPTARG; do
				label_str+="$label"	
			done
			gh search issues -- "lable:$lable_str"	
			;;
		?/)
			echo "bro what"
			;;
	esac	
done
